# Generated by Django 2.1.3 on 2018-12-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrs',
            name='location_of_the_car',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carrs',
            name='mileage',
            field=models.CharField(max_length=50),
        ),
    ]
